MaterialXamlToolKit.Avalonia.DeepPurple/RadioButton.xaml
MaterialXamlToolKit.Avalonia.DeepPurple/TextBox.xaml
MaterialXamlToolKit.Avalonia/RadioButton.xaml
MaterialXamlToolKit.Avalonia/TextBox.xaml

Radiobutton ripple

---

AvaloniaRipple.sln
AvaloniaRipple/App.xaml
AvaloniaRipple/AvaloniaRipple.csproj
Material.Avalonia/Material.Avalonia.DeepPurple.xaml
Material.Avalonia/Material.Avalonia.DeepPurple.xaml.cs
Material.Avalonia/Material.Avalonia.Templates.xaml
Material.Avalonia/Material.Avalonia.Templates.xaml.cs
Material.Avalonia/Material.Avalonia.csproj

add project soon ll be ready to create nuget

add new project

---

Material.Demo/MainWindow.xaml
Material.Styles/FloatingButton.xaml

Fix floating button

---

Material.DataGrid/DataGrid.xaml

This patch will improve hit-test DataGridColumnHeader too
https://user-images.githubusercontent.com/38249047/104087773-7e7af180-52a5-11eb-98de-57ad9fff0f1c.mp4

Add feedback when selected / pointerover DataGridRow

---

Material.Demo/MainWindow.xaml
Material.Demo/MainWindow.xaml.cs
Material.Demo/Pages/ButtonsDemo.axaml
Material.Styles/Card.xaml
Material.Styles/Card.xaml.cs
Material.Styles/Slider.xaml

In this PR will improve bubble of slider. I noticed about ugly implements of bubble (will appear problem like incorrect alignment of inner text) so I tried to fix this. Also I created an property for allow / disallow clipping inside contents for some cases. Demo will improved slightly too for example: Shadow under ColorZone will be fixed due incorrect Z-Index.
Inner text of bubble will keep align in center:
ColorZone Z-Index has changed to 1 for fix shadow:

A few improvements of features

---

Material.Avalonia/Material.Avalonia.csproj
Material.Demo/MainWindow.xaml
Material.Demo/MainWindow.xaml.cs
Material.Demo/Pages/ButtonsDemo.axaml
Material.Styles/Card.xaml
Material.Styles/Card.xaml.cs
Material.Styles/Slider.xaml

Release v1.0.1

---

Material.Demo/Pages/FieldsDemo.axaml
Material.Styles/ButtonSpinner.xaml
Material.Styles/NumericUpDown.xaml
Material.Styles/RepeatButton.xaml

Default:  
Focused:  
Also closes #59

Numeric up down rework

---

Material.Styles/Separator.xaml

Vertical separator style realization

---

Material.Styles/MenuItem.xaml

Fixes #142 (see explanation in issue description).

Fix context menu submenu opening and closing in infinite loop (#142)

---

Material.Dialog/Views/AlertDialog.axaml
Material.Dialog/Views/CustomDialog.axaml
Material.Dialog/Views/DatePickerDialog.axaml
Material.Dialog/Views/TextFieldDialog.axaml
Material.Dialog/Views/TimePickerDialog.axaml

closes https://github.com/AvaloniaCommunity/Material.Avalonia/issues/146

Set KeyboardNavigation.TabNavigation property to Continue on ItemsPresenter in every DialogView

---

Material.Styles/Themes/SystemThemeProbe.cs

fix: Inherited theme on Windows11 was reversed

---

Material.Styles/Resources/Themes/ToggleSwitch.axaml

Closes #255 
I'm using formatting tools so feel free to re format it.

fix: update ToggleSwitch animation.

---

Material.Avalonia.DataGrid/Material.Avalonia.DataGrid.csproj
Material.Avalonia.Dialogs/Material.Avalonia.Dialogs.csproj

adds the icon also to the DataGrid and Dialogs package and added tags to these packages (same as main package plus "datagrid"/"dialogs")

Added package icon and tags for DataGrid and Dialogs package

---

README.md

The previously linked repository has been archived and links back to the updated one.

Update link for Material.Icons

---

Directory.Packages.props
Material.Avalonia.Demo.Browser/Material.Avalonia.Demo.Browser.csproj
Material.Avalonia.Demo.Desktop/Material.Avalonia.Demo.Desktop.csproj
Material.Styles/Controls/Clock.axaml
Material.Styles/Controls/Scroller.axaml
Material.Styles/Resources/Compatibility/ButtonClasses.axaml
Material.Styles/Resources/Compatibility/ProgressBarClasses.axaml
Material.Styles/Resources/Compatibility/RadioButtons.axaml
Material.Styles/Resources/Compatibility/ScrollViewerClasses.axaml
Material.Styles/Resources/Compatibility/SeparatorClasses.axaml
Material.Styles/Resources/Compatibility/SliderClasses.axaml
Material.Styles/Resources/Compatibility/TabControlClasses.axaml
Material.Styles/Resources/Compatibility/TextBlockClasses.axaml
Material.Styles/Resources/Compatibility/TextBoxClasses.axaml
Material.Styles/Resources/Compatibility/ToggleButtons.axaml
Material.Styles/Resources/Themes/ScrollViewer.axaml
Material.Styles/Resources/Themes/Slider.axaml
Material.Styles/Resources/Themes/TabControl.axaml
Material.Styles/Resources/Themes/TextBlock.axaml
Material.Styles/Resources/Themes/TextBox.axaml

- Update Avalonia dependency to 11.1
- Removes the unnecessary resources imports inside other resource files

Avalonia 11.1

---

Material.Styles/MaterialToolKit.xaml
Material.Styles/Resources/Themes/MenuFlyoutPresenter.axaml
Material.Styles/Resources/Themes/MenuItem.axaml
Material.Styles/Resources/Themes/TextBox.axaml
Material.Styles/Resources/Themes/TextSelectionHandle.axaml

Implement Text Selection handles in TextBox for touch input

---

Material.Avalonia.DataGrid/Material.Avalonia.DataGrid.csproj
Material.Avalonia.Dialogs/Material.Avalonia.Dialogs.csproj

Changes dependency for DataGrid and Dialogs to Material.Avalonia instead of Material.Styles
Fixes #389

Changes dependency for DataGrid and Dialogs to Material.Avalonia

---

Material.Avalonia.DataGrid/Material.Avalonia.DataGrid.props

Fix DataGrid AOT compilation

---

Material.Avalonia.Demo/Pages/TreeViewsDemo.axaml

This adds in a ShowMeTheXAML wrapper on the tree view page.

Adding ShowMeTheXAML support to TreeView Page

---

Material.Avalonia.Demo/MainView.axaml

can we perhaps order the items in the drawer alphabetically in the demo app?
I'm new to this library and when checking out the demo I often get lost in the menu when looking for something specific.

order menu items alphabetically in demo app

---

Material.Styles/Resources/Themes/MenuItem.axaml

Remove usage of missing MaterialAccessText in MenuItem

---

Material.Avalonia.Demo/Pages/ComboBoxesDemo.axaml
Material.Styles/Resources/Themes/ComboBox.axaml

Initial implementation before full rework

Add validation support for ComboBoxes. Fixes #166

---

Material.Styles/Resources/Themes/ContentControl.axaml
Material.Styles/UserControl.axaml

Adds the CornerRadius support for ContentControl and UserControl

---

Material.Styles/MaterialToolKit.xaml
Material.Styles/Resources/Themes/HeaderedContentControl.axaml

Add missing control theme `HeaderedContentControl` implementation, the panel which used is `DockPanel` which allows you to modify header position by using `Styles`
- Add `HeaderedContentControl.axaml`

Add missing HeaderedContentControl control theme

---

Material.Avalonia.Demo/ViewModels/DialogDemoViewModel.cs
Material.Avalonia.Dialogs/DateTimePickerDialogBuilderParams.cs
Material.Avalonia.Dialogs/DialogHelper.cs
Material.Avalonia.Dialogs/ViewModels/DatePickerDialogViewModel.cs
Material.Avalonia.Dialogs/ViewModels/TimePickerDialogViewModel.cs
Material.Avalonia.Dialogs/Views/DatePickerDialog.axaml
Material.Avalonia.Dialogs/Views/DatePickerDialog.axaml.cs
Material.Avalonia.Dialogs/Views/TimePickerDialog.axaml
Material.Avalonia.Dialogs/Views/TimePickerDialog.axaml.cs

Due to https://github.com/AvaloniaCommunity/Material.Avalonia/issues/470

Add temporary obsoletion messages for DatePickerDialog and TimePickerDialog
