AvaloniaCommunity/Material.Avalonia

Material.Dialog/ViewModels/DialogWindowViewModel.cs
Material.Dialog/ViewModels/TextField/TextFieldViewModel.cs
Material.Dialog/ViewModels/ViewModelBase.cs

This PR is really simple, it just renames the:
Material.Dialog.ViewModels.ViewModelBase => Material.Dialog.ViewModels.DialogViewModelBase
So it does not conflict with the local ViewModelBase

Renaming ViewModelBase => DialogViewModelBase

---

Material.Styles/Separator.xaml

`Separator` had wrong background binding and all was filled with `MaterialDesignSelection`. Also now `Rectangle` takes color from `BorderBrush`
Before (no green):
After:
Final:

Separator background fixed

---

Material.Styles/ProgressBar.xaml

Seems the currently used style does not stop the Rotator#PART_Rotator from rotating when IsIndeterminate="True". Found this using GPU resources in the background despite not being on screen. This fixes that by updating that current animation to override the Speed property for the entire duration of animation, forever.

Stop Spinner from rotating when hidden.

---

Material.Demo/Models/SideSheetDemoViewModel.cs
Material.Demo/Pages/SideSheetDemo.axaml
Material.Styles/SideSheet.xaml
Material.Styles/SideSheet.xaml.cs

Added `SideSheetHeaderProperty` and `SideSheetHeaderTemplateProperty` to define a header. Default template uses `<TextBlock Classes="Headline6"/>`. The `header` got a default `Button` bound to `SideSheetCanCloseProperty` to optional hide it. `SideSheetPaddingProperty` is used to give the `SideSheet` a seperate padding, while `Padding` is used for the content itself.
Where I am not sure right now is the connection of the `Button.Click` event to `SideSheetOpened`, see https://github.com/AvaloniaCommunity/Material.Avalonia/pull/154/commits/0d87a7e5f60d79ad2b64b47318e26e2addd60ba3#diff-f838b3d7b88edbe939d368b78bdac101af001ae766cfd8e6530208efc6dd549aR152
Also demo and preview in the template adapted.
fix #145

SideSheet: Possibility to define a header added with the corresponding properties.

---

Material.Styles/MaterialToolKit.xaml

Currently, the Material DatePicker implementation is non-functional. However, the inclusion of the Material styles into a project heavily interferes with either providing a custom style for DatePicker, or just utilizing the Avalonia.Themes.Simple. The way <themes:MaterialTheme /> is structured, it is not possible to exclude styles for particular controls, and themes:BundledTheme isn't supported anymore. As such, the style declaration for DatePicker should be removed, until a time where both DatePicker and TimePicker have consistent and functional styling Material.Avalonia.

Exclude non-functional DatePicker from styles collection

---

Material.Demo/Pages/ComboBoxesDemo.axaml
Material.Styles/MaterialToolKit.xaml
Material.Styles/Resources/Themes/ComboBox.axaml
Material.Styles/Resources/Themes/ComboBoxItem.axaml

Migrate_Combobox

---

Material.Styles/Converters/BrushRoundConverter.cs

These are used for the named colors built into Avalonia
I am contributing this on behalf of Garmin ©. Our legal team needs me to disclose that we are contributing this code under the [MIT license](https://github.com/AvaloniaUI/Avalonia/blob/2ab5f8b8932e0acac078a58c30ff8db908d9a9d8/licence.md) that this project used at the time of contribution.

Feature: BrushRoundConverter supports ImmutableSolidColorBrush objects

---

Material.Demo/MainWindow.axaml
Material.Demo/Material.Demo.csproj
Material.Demo/Pages/SnackbarDemo.axaml
Material.Demo/Pages/SnackbarDemo.axaml.cs
Material.Styles/Controls/SnackbarHost.axaml

Fixes the width of snachkbar from the fixed value fo 344 to an minimum width.
also fixe the vertical text alignment which looked wrong if e.g. a button is shown (top aligned vs center).
Also adds a demo page for snackbarhost
fixes #352

Fix layout of snackbar (width and text alignment)

---

Material.Styles/Resources/Themes/ToggleSwitch.axaml

I added handler for LeftHeader class for ToggleSwitch to comply with demo project.
For some reason it wasn't there, i added this style and checked in my project, it worked as expected

Fix for LeftHeader class for ToggleSwich

---

Material.Styles/Resources/Themes/ProgressBar.axaml

Fixed a bug causing the corner radius that are set to a ProgressBar, not being applied to the top left and the bottom left corners.

Fix for the progress bar corner radius issue #372

---

Material.Avalonia.Demo/MainView.axaml
Material.Avalonia.Demo/Pages/ButtonsDemo.axaml
Material.Avalonia.Demo/Pages/ColorZonesDemo.axaml
Material.Avalonia.Demo/Pages/Home.axaml
Material.Avalonia.Demo/Pages/TogglesDemo.axaml
Material.Styles/Resources/Themes/Button.axaml
Material.Styles/Resources/Themes/ComboBox.axaml
Material.Styles/Resources/Themes/DatePicker.axaml
Material.Styles/Resources/Themes/TextBox.axaml
Material.Styles/Resources/Themes/TimePicker.axaml
Material.Styles/Resources/Themes/ToggleButton.axaml

- Rework ToggleButtons: Material, Outline, Flat, Icon control themes are supported:
- Rework Button Flat style to make it consistent across buttons
- By default MaterialFlatButton will inherit Foreground (previously it use primary colors)
- Added the `primary` class to use primary colors
- Click feedback color now use Foreground color

ToggleButtons rework

---

Material.Avalonia/Material.Avalonia.csproj

Prevent the Numerge.MSBuild leaking as the dependency to Material.Avalonia

Prevent the Numerge.MSBuild leaking as the dependency

---

Material.Styles/Resources/Themes/ToggleButton.axaml

It just brings back the missing
```
Background="{TemplateBinding Background}"
```
on
```xml
<Border Name="PART_RootBorder"
```
for ToggleButton

Fix ToggleButton Background Not Bound

---

Material.Styles/Controls/SideSheet.axaml
Material.Styles/Resources/Themes/Button.axaml

- Make .icon buttons background transparent
- Replace Theme for MaterialIconButton in SideSheet closing button
Fixes #397

Make .icon buttons background transparent

---

Material.Styles/Resources/Themes/NotificationCard.axaml

added the light, dark and accent style classes (I think they are called?) to the `NotificationCard`s ControlTheme so the `Background` can be controlled like the following:
```csharp
var topLevel = TopLevel.GetTopLevel(this);
WindowNotificationManager? _manager = new WindowNotificationManager(topLevel);
_manager.Show("Notification with \"light\" class", NotificationType.Error, classes: ["light"]);
_manager.Show("Notification with \"dark\" class", NotificationType.Error, classes: ["dark"]);
_manager.Show("Notification with \"accent\" class", NotificationType.Error, classes: ["accent"]);
```
Result:
this should fix #417, at least I think this is the correct change for the API

fix 417 - NotificationCard Background

---

Material.Avalonia.DataGrid/DataGrid.xaml

Addresses the question #431 / issue #432
Basically a copy-paste of the TreeView style

Adapt the TreeView's expander for the DataGrid groups.

---

Material.Styles/Resources/Themes/ComboBox.axaml

I think centering the place holder text in the default combobox style makes more sense?

Centered place holder text in combobox

---

Material.Avalonia.Demo/MainView.axaml
Material.Avalonia.Demo/Material.Avalonia.Demo.csproj
Material.Avalonia.Demo/Pages/FieldsLineUpDemo.axaml
Material.Avalonia.Demo/Pages/FieldsLineUpDemo.axaml.cs
Material.Avalonia.Demo/ViewModels/FieldsLineUpDemoViewModel.cs

I added a "Fields line up" to the demo app, like we have in [MDIX](https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit).
I think this gives quite a nice overview of all the controls :smile:

Add fields line up demo

---

Material.Avalonia.Demo/Pages/FieldsLineUpDemo.axaml
Material.Styles/Resources/Themes/TextBox.axaml

fixes an issue where the `Watermark` overlaps the `TextFieldAssist.Label` if the `FilledTextBox` style is used, the TextBox is not focused and the TextBox is empty.
Additionally the "PasswordBoxes" in the new demo page now show the `PasswordChar="*"`

hide watermark when the FilledTextBox is not focused

---

Material.Styles/Resources/Themes/ProgressBar.axaml

Until https://github.com/AvaloniaUI/Avalonia/issues/18616 fixed

Temporary remove linear ProgressBar transitions due to avalonia bug. #445

---

Material.Avalonia.Demo/Pages/ButtonsDemo.axaml
Material.Avalonia.Demo/Pages/ButtonsDemo.axaml.cs
Material.Styles/Assists/ButtonAssist.cs
Material.Styles/MaterialToolKit.xaml
Material.Styles/Resources/Themes/HyperlinkButton.axaml
Material.Styles/Resources/Themes/ToolTip.axaml
Material.Styles/Themes/Base/MaterialPredefinedBaseColors.axaml

Add Hyperlink themes, which it doesn't existed before.
Static Resource key: `MaterialHyperlinkButton`
Commit: https://github.com/AvaloniaCommunity/Material.Avalonia/commit/d81e934828305331611afc6b3a28a2ba435b4eea
Dark theme
Light theme
Adds two new brushes:
- `MaterialHyperlinkBrush` brush for initial state hyperlinks
- `MaterialHyperlinkVisitedBrush` brush for visited (clicked) state hyperlinks
Adds two new colours:
- `MaterialHyperlinkColor` initial hyperlink colour
- `MaterialHyperlinkVisitedColor` visited hyperlink colour
Commit: https://github.com/AvaloniaCommunity/Material.Avalonia/commit/71fd15ef9e9832b7ad2c5badfeef97244f88451e
Tips: those colours have different between light and dark theme
Also, this PR will update Demo buttons page

Add HyperlinkButton theming support

---

Material.Styles/Resources/Themes/ComboBox.axaml

Fixed `MaterialOutlineComboBox` control theme.
While using this library, I noticed that the outlined combobox should have lighter colored border brush like the outlined textbox but is body colored.
This fix sets the outlined combobox to the same border brush as the outlined textbox and tweaks the foreground of the label that is affected by it.
Transitions when getting focus were also missing, so I also added them to be like the TextBox.
I am a newbie to Avalonia and Material.Avalonia, so please tell me any mistakes.
|Before|After|
|-|-|
|![image](https://github.com/user-attachments/assets/bd865e4c-0fcf-4323-b206-6168e1b49560)|![image](https://github.com/user-attachments/assets/380f749c-137a-4219-a289-f8c88dba21d7)|
|![image](https://github.com/user-attachments/assets/1cdf4cd4-e0cc-42a0-855 …

Fix outlined ComboBox border styles

---

Material.Avalonia.Demo/App.axaml.cs
Material.Avalonia.Demo/Assists/AutomationAssist.cs
Material.Ripple/RippleEffect.cs
Material.Styles/Controls/FloatingButton.axaml

This will make `RippleEffect` usable as a element that can guide user which things are they looking for, or make it raisable by keyboard or any source.
- `RippleEffect.RaiseRipple` Raise a ripple element at the coordinate. By default it will raise at center point of the bound of `RippleEffect` control
- parameter `double nX = 0.5` normalised X coordinate, valid range: [0.0 - 1.0] 
- parameter `double nY = 0.5` normalised Y coordinate, valid range: [0.0 - 1.0]
- `RippleEffect.RaiseRippleAbsoluteCoord` Raise a ripple element at the non-normalised coordinates. (acquired by https://github.com/AvaloniaCommunity/Material.Avalonia/pull/453#discussion_r2072168285)
- parameter `double x` X coordinate, should be in bounds of the `RippleEffect`
- parameter `double y` Y coordinate, should be in …

Expose RippleEffect.RaiseRipple and RaiseRippleAbsoluteCoord function

---

Material.Avalonia.Demo.Desktop/Program.cs
Material.Avalonia.Demo/Pages/ButtonsDemo.axaml
Material.Avalonia.Demo/Pages/DialogDemo.axaml
Material.Avalonia.Demo/Pages/DialogDemo.axaml.cs
Material.Styles/MaterialToolKit.xaml
Material.Styles/Resources/Themes/DropDownButton.axaml
Material.Styles/Resources/Themes/FlyoutPresenter.axaml
Material.Styles/Resources/Themes/ManagedFileChooser.axaml
Material.Styles/Resources/Themes/SplitButton.axaml

This PR will add missing control themes that avaloniaUI shipped new controls `SplitButton`, `DropDownButton`, and a dialog theme `ManagedFileChooser` that mentioned in pinned issue #234, and correct `FlyoutPresenter` had no background brush which should have background brush while other themes do that.
- Add `SplitButton.axaml` with Raised (default) and Outline variant, usable Themes: `MaterialSplitButton` (default), `MaterialOutlineSplitButton`, both supports `.up` (default) and `.down` classes to change arrow direction, also customise is allowed too by using some tricky style selector to override.
- Add `DropDownButton.axaml` with Raised (default) and Outline variant, usable Themes: `MaterialDropDownButton`  (default), `MaterialOutlineDropDownButton`
- Add `ManagedFileChooser.axaml` …

Add some missing control themes (SplitButton, DropDownButton, ManagedFileChooser), correct FlyoutPresenter

---

Material.Ripple/RippleEffect.cs
Material.Ripple/RippleHandler.cs

This PR will correct some `RippleHandler` renderer abnormal behaviours, which may happens some graphical issues while effects is working, also adding `FadeOutDuration` property to allow users to control how long it take to fade out.
- `RippleEffect.FadeOutDuration` duration for second state (fade-out)
- Rewrote procedure and algorithm in `RippleHandler`, thanks again to @maxkatz6 for converting this effect to custom renderer handler way.
- `RippleEffect.FadeOutDuration` should not higher than `Ripple.Duration`, otherwise Ripple effect will be deleted early.

Improved Ripple visual effect

---

Material.Ripple/RippleHandler.cs

CI/CD didnt detect `Math.Clamp` is not exist in netstandard, now push hotfix to resolve that problem

hotfix: Math.Clamp is not existed in netstandard (RippleHandler)

---

Material.Styles/Controls/FloatingButton.axaml
Material.Styles/Resources/Themes/Button.axaml
Material.Styles/Resources/Themes/ComboBox.axaml
Material.Styles/Resources/Themes/ComboBoxItem.axaml
Material.Styles/Resources/Themes/Expander.axaml
Material.Styles/Resources/Themes/HyperlinkButton.axaml
Material.Styles/Resources/Themes/ListBoxItem.axaml
Material.Styles/Resources/Themes/Menu.axaml
Material.Styles/Resources/Themes/MenuItem.axaml
Material.Styles/Resources/Themes/SplitButton.axaml
Material.Styles/Resources/Themes/TextBox.axaml
Material.Styles/Resources/Themes/ToggleButton.axaml

Technical Changes
- Added focus state handling in some templates
- Extended ripple effect system to support focus state
- Disabled default focus adorner in favor of Material Design visuals
- Added smooth transitions for focus state changes

Add keyboard focus visual indicator for some controls
